"""
Normative terminology, colour scheme, and label conventions for the twin-primes project.

Generated by notebook/terminology.ipynb. Edit there, not here.
"""

import math

# ---------------------------------------------------------------------------
# Colour scheme
# ---------------------------------------------------------------------------

#: Canonical colours by semantic role.
COLOURS = {
    # Ball metaphor: structural roles
    "seed":        "#000000",   # {1,2,3} — black centre
    "surface":     "#4477AA",   # depth=0 (current surface) — blue
    "deep":        "#CC3311",   # depth=max — red
    "satellite":   "#AAAAAA",   # X exceptions at 2× surface radius — grey
    # Non-ball roles (existing conventions preserved)
    "prediction":  "darkorange",  # HL / reference curves
    "anomaly":     "red",         # exceptions, failures, threshold markers
    "primary":     "steelblue",   # primary data curves
    "lower":       "green",       # lower bounds, minority classes
    "reference":   "black",       # grid lines, diagonals
}


def depth_colour(depth: int, max_depth: int) -> str:
    """
    Return a hex colour for an element at `depth` layers below the current surface,
    where `max_depth` is the depth of the deepest (oldest) layer.

    Colour interpolates red→blue on a log scale:
      depth=0        → COLOURS['surface'] (blue)
      depth=max_depth → COLOURS['deep']   (red)

    Args:
        depth:     number of generations below the current surface (0 = surface)
        max_depth: depth of the oldest generation

    Returns:
        Hex colour string, e.g. '#7A5599'
    """
    if max_depth <= 0:
        return COLOURS["surface"]

    # Normalised position on [0, 1]: 0=surface (blue), 1=deepest (red)
    t = math.log(depth + 1) / math.log(max_depth + 1)
    t = max(0.0, min(1.0, t))

    # Parse surface (blue) and deep (red) hex colours
    def parse_hex(h):
        h = h.lstrip("#")
        return tuple(int(h[i:i+2], 16) for i in (0, 2, 4))

    r0, g0, b0 = parse_hex(COLOURS["surface"])   # blue end (t=0)
    r1, g1, b1 = parse_hex(COLOURS["deep"])       # red end  (t=1)

    r = round(r0 + t * (r1 - r0))
    g = round(g0 + t * (g1 - g0))
    b = round(b0 + t * (b1 - b0))

    return f"#{r:02X}{g:02X}{b:02X}"


# ---------------------------------------------------------------------------
# Display labels
# ---------------------------------------------------------------------------

#: Human-readable display labels for sets and variables.
LABELS = {
    # Sets
    "A":   r"$\mathcal{A}$ (A002822, twin prime witnesses)",
    "B":   r"$\mathcal{B} = U \cup L \cup N$ (visited non-twin witnesses)",
    "U":   r"$U$ (upper witnesses, A121765 $\cap\, \mathcal{S}$)",
    "L":   r"$L$ (lower witnesses, A121763 $\cap\, \mathcal{S}$)",
    "N":   r"$N$ (null witnesses, A060461 $\cap\, \mathcal{S}$)",
    "X":   r"$\mathcal{X}$ (exceptions, A243956 $\setminus \{1\}$)",
    "S":   r"$\mathcal{S}$ (visited set)",
    "seed": r"seed $\{1, 2, 3\}$",
    # Variables
    "w":   r"$w$ (twin prime witness)",
    "u":   r"$u$ (additive component, $u + v = w$)",
    "v":   r"$v$ (additive component, $u + v = w$)",
    "V":   r"$V = \max(\mathcal{A}_g)$ (BC threshold; $v \approx V$ in lopsided regime)",
    "g":   r"$g$ (generation index)",
    "r":   r"$r = (v-u)/w$ (gap ratio)",
    "r/w": r"$r$ (normalised gap ratio, $r = (v-u)/w$)",
    "C2":  r"$C_2 \approx 0.6601618$ (twin prime constant)",
    # Conjectures
    "BC":      "Bridging Conjecture (BC)",
    "MNC":     "Middle Number Conjecture (MNC)",
    "AIWBTP":  "All Integers Witnessed By Twin Primes (AIWBTP)",
    "HLC":     "Hardy-Littlewood Conjecture (HLC)",
    "SIC":     "Selcoe's Interval Conjecture (SIC)",
    "TPC":     "Twin Prime Conjecture (TPC)",
}

# ---------------------------------------------------------------------------
# Conjecture statements (canonical one-line forms)
# ---------------------------------------------------------------------------

CONJECTURES = {
    "TPC":    r"$\mathcal{A}$ is infinite",
    "BC":     r"$\forall V \in \mathbb{N}\ \exists u, v, w \in \mathcal{A}$ with "
              r"$u \leq v \leq V < w$ and $u + v = w$",
    "MNC":    r"$\forall w \in \mathcal{A}\ \exists u, v \in \mathcal{A}$ with "
              r"$u, v < w$ and $u + v = w$",
    "AIWBTP": r"Every $w \in \mathbb{N}$ is in $\mathcal{A} + \mathcal{A}$, "
              r"with exactly 12 exceptions (all $w \leq 701$, including $w=1$)",
    "HLC":    r"$\pi_2(x) \sim 2C_2\, x / (\ln x)^2$, $C_2 \approx 0.6601618$",
    "SIC":    r"$\forall k \geq 1\ \exists w \in \mathcal{A}$ with $5k \leq w \leq 7k$",
}
